// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1wt1i7f9hp2X95rPGE4ic5fxIyomEbw',
    appId: '1:592956308849:web:732a33ef4a33de1c7b8ad0',
    messagingSenderId: '592956308849',
    projectId: 'farmer-citi',
    authDomain: 'farmer-citi.firebaseapp.com',
    storageBucket: 'farmer-citi.appspot.com',
    measurementId: 'G-K15ZQ1CRX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOXuvcnZumNlB9M3afuWMHKGb7gEtUw9I',
    appId: '1:592956308849:android:22f7b077c94c246a7b8ad0',
    messagingSenderId: '592956308849',
    projectId: 'farmer-citi',
    storageBucket: 'farmer-citi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8e60gQkNRGFp4vUh37Lzler9xKgzDM98',
    appId: '1:592956308849:ios:b3c86319ff709de67b8ad0',
    messagingSenderId: '592956308849',
    projectId: 'farmer-citi',
    storageBucket: 'farmer-citi.appspot.com',
    iosBundleId: 'com.example.firmerCity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8e60gQkNRGFp4vUh37Lzler9xKgzDM98',
    appId: '1:592956308849:ios:b3c86319ff709de67b8ad0',
    messagingSenderId: '592956308849',
    projectId: 'farmer-citi',
    storageBucket: 'farmer-citi.appspot.com',
    iosBundleId: 'com.example.firmerCity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN1wt1i7f9hp2X95rPGE4ic5fxIyomEbw',
    appId: '1:592956308849:web:671fd989112668bb7b8ad0',
    messagingSenderId: '592956308849',
    projectId: 'farmer-citi',
    authDomain: 'farmer-citi.firebaseapp.com',
    storageBucket: 'farmer-citi.appspot.com',
    measurementId: 'G-4G10PRNVT0',
  );
}
